version: '3.8'

services:
  web:
    build: .
    container_name: speed-test-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    restart: unless-stopped
    networks:
      - default
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  default:
    driver: bridge
